language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - check
    - libssl-dev
    - lcov
before_install:
 - sudo apt-get update -qq
 - sudo pip install codecov
script: 
 - autoreconf -i && ./configure --enable-code-coverage && make && make check-code-coverage
after_success:
  - codecov
